name: personalized_bottom_navbar
description: "A custom bottom navigation bar package for Flutter, supporting enums and custom widgets."
version: 0.0.2
homepage: https://github.com/hs-dev1/personalized_bottom_navbar/tree/master


environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
